GET http://localhost:3000/api/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGVhZTQ3NjcyMzY5NmZmY2ZlN2Y1YjkiLCJpYXQiOjE2OTMxMTU5ODMsImV4cCI6MTY5MzExNjg4M30.RZmcousevI0MeCGOZbAKTBIiVT5yawAKCHnl5Sw5NEM
###

POST http://localhost:3000/api/employee/create-emloyee
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGU3Nzc0N2E3OWMxYWRlMjJlODE1N2EiLCJpYXQiOjE2OTMxMTU0NDIsImV4cCI6MTY5MzExNjM0Mn0.nmielG58sShO_yT4wc6CDVSpRcgnVE-Rr1K5Pbdvqu8

{
    "fullName": "Admin",
    "username": "admin",
    "email": "admin@gmail.com",
    "phoneNumber": "0123456789",
    "address": "Viet Nam",
    "position": "Admin",
    "salary": 200000,
    "password": "1234567"
}

###

GET http://localhost:3000/api/auth/account
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGU3NzhlNmZiNWQ5NmYxZmY3NzEwNjMiLCJpYXQiOjE2OTM0NjMxMzMsImV4cCI6MTY5MzQ2NDAzM30.4HeyRb6g_Dy2VhkLKQV6lHpKh0YAMhVknT8k4_Xhtws

